### ISSUE TITLE
Issues and Solutions tab repeats twice

### ISSUE THREAD

**Issue by Shaische** [openpnp/openpnp#1415] opened 2022-05-17 05:02 UTC
# Problem Report
## Describe the Issue
Pretty sure this issue was submitted before but cannot find it. This is a UI bug. The issues and solutions tab is repeated twice where it should say "Log" in the tab instead. This is on a fresh install of latest stable OpenPNP with a clean machine.xml file. See attached image.

On a (related?) note, any highlighted/selected tab is whited out and becomes hard to see. Attached image.

## Steps to reproduce
MacOS Monetery 12.0.1 (latest)

<img width="342" alt="screenshot_580" src="https://user-images.githubusercontent.com/2673147/168732814-07af5cd6-7eba-417b-a425-9a500cb6cdbc.png">
<img width="190" alt="screenshot_581" src="https://user-images.githubusercontent.com/2673147/168733202-5dfefe7f-13d7-4ace-9c23-fa8ed4b49244.png">

**Comment by markmaker** [comment] 2022-05-17 09:05
Duplicate of #1199.

Seems to be a bug in the MacOS theming. 

A workaround is here:
https://github.com/openpnp/openpnp/issues/1199#issuecomment-918392848

_Mark

**Closed by markmaker** 2022-05-17 09:05 UTC

**Comment by Shaische** [comment] 2022-05-18 00:55
@markmaker Why is the other issue closed then if it still exists?

**Comment by markmaker** [comment] 2022-05-18 07:47
I thought I close it, because there is a workaround solution to it. 

AFAIK it is not our problem, but that of the MacOS theming. It does not seem to support dynamically changing tab titles, on some but not all Mac machines. Because I don't use a Mac, I also can't explore this further. 

@vonnieda, should we keep Issues open in such cases?

_Mark

**Comment by vonnieda** [comment] 2022-05-18 20:53
It's fine to leave it open for a while. Maybe someone wants to investigate it further.

**Comment by Shaische** [comment] 2022-05-19 01:43
It's not just the name being copied over. All highlighted tabs have white text, making it hard to see what the tab says. See attached image. I think these two issues are related?

<img width="190" alt="screenshot_581" src="https://user-images.githubusercontent.com/2673147/169185770-afaa794a-d618-40c3-9c75-b8a114b4308a.png">
.
