### ISSUE TITLE
Bottom side PCB co-ords

### ISSUE THREAD

**Issue by tracklogic** [openpnp/openpnp#479] opened 2017-03-24 13:35 UTC
I keep meaning to look into this / ask the question but keep getting side tracked.

Might be me doing something daft but i seem to think if i put a board in the jig, do fiducial match, board location is all ok with the side? combo box set to "top". If i then flip the board over in the jig and set the combo box to "bottom" if i click "move camera to board location" the head goes off to the right quite a bit, like the x,y co-ordinates need the sign flipping over or something?

Matt

**Comment by vonnieda** [comment] 2017-03-24 14:21
It's a bit complicated. It's documented here https://github.com/openpnp/openpnp/wiki/Understanding-Board-Locations.

Also be aware that there is currently a bug with bottom coordinates in certain conditions: https://github.com/openpnp/openpnp/issues/403

This seems to be more of a question than an issue, so I'm going to close it. If you are running into a specific problem that is different than that one I linked, please open a new issue with reproduction information.

**Closed by vonnieda** 2017-03-24 14:21 UTC
