### ISSUE TITLE
 change in feeder pick location, not taken into account.

### ISSUE THREAD

**Issue by JulienDevillers** [openpnp/openpnp#1016] opened 2020-05-28 14:47 UTC
Last version of develop [branch](url)

# Problem Report
## Describe the Issue
A change by typing  coordinates of pick location is not taken into account when "move tool to
the selected feeder's current pick location".

## Steps to Reproduce
- open the joined machine.xml.
- connect and zero the machine
- goto to feeders panel
- click on feeder2
- see that Z for pick location is -26
- click on the button "move tool to the selected feeder's current pick location."
- check on tool coordinates, in status bar that  Z is  -26
- set  Z for pick location to -28.
- click apply
- select another feeder and go back to feeder2
- see that Z for pick location is -28 as it should
- click on the button "move tool to the selected feeder's current pick location."
- check on tool coordinates, in status bar, Z is -26 while it should be -28.

If I close the app and restart, new coordinates are taken into account.

## Expected Result
tool should go to the new coordinates.

[machine.zip](https://github.com/openpnp/openpnp/files/4696263/machine.zip)
[OpenPnP.0.log.zip](https://github.com/openpnp/openpnp/files/4696267/OpenPnP.0.log.zip)

Whenever possible, please use the Menu -> Help -> Submit Diagnostics feature and include the URL here. Submit Diagnostics makes it easy to include log files, screen capture, debug images, configuration files, etc.

-> bad api key.

**Comment by doppelgrau** [comment] 2021-04-18 23:48
Duplicate of #1109 ?!
Pick location is only updated after a feed operation (can argue if that's good or not, but since a feed operation can be "expensive" it makes somehow sense.)

**Comment by markmaker** [comment] 2022-07-23 07:54
`pickLocation` should be made a local variable of `getPickLocation()` initialized to `location`. It is reset in each call to `feed()` I see no sensible use of this copy.

_Mark

**Comment by markmaker** [comment] 2022-07-23 08:13
But for the `ReferenceStripFeeder` that the OP referred to, I see no redundancy. Maybe it was solved in #1031. 

I also cannot reproduce it.

_Mark

**Comment by markmaker** [comment] 2022-07-23 08:49
See #1449.

**Comment by markmaker** [comment] 2022-07-23 08:51
Closing this as no longer reproducible for `ReferenceStripFeeder` and solved by #1449 for `ReferenceDragFeeder`. 
_Mark

**Closed by markmaker** 2022-07-23 08:51 UTC

**Comment by surabibio** [comment] 2022-07-24 11:25
Wow and Thanks
