### ISSUE TITLE
Dialog boxes pop under instead of over the current page on Mac

### ISSUE THREAD

**Issue by GeoSaffer** [openpnp/openpnp#1255] opened 2021-08-19 12:09 UTC
Popup confirmation dialogs like   Do you want to save ?  with Yes No Cancel buttons will pop under the active page and you have to sometimes click a few times on the active page to have it show in front of it.

To reproduce:
Use a Mac
open any calibration pipeline page 
make a change 
close it
when it ask if you want to save changes it will be behind the page 
click on the Calibration Pipeline page a few time for it to show

**Comment by markmaker** [comment] 2021-08-19 15:42
Duplicate of #1222 

Please continue there.

_Mark

**Closed** 2021-08-19 15:42 UTC
