### ISSUE TITLE
Error when no dispenser configured

### ISSUE THREAD

**Issue by dzach** [openpnp/openpnp#406] opened 2017-01-11 10:38 UTC
When there is no dispenser configured, machine cannot proceed to job execution. Gives an error message.

Error message:
```
No default paste dispenser available on head H1.
<Try again> <Pause job>
```

I know this is work in progress. I'm just reporting it here for the record.

**Comment by vonnieda** [comment] 2017-01-11 14:43
What type of job? Please provide steps to reproduce.

If it's a paste job I think it's okay that a dispenser is required to be defined.

**Comment by dzach** [comment] 2017-01-11 23:11
Any type of job. It doesn' execute a single step, no matter what.

**How to reproduce**:

1. Start with a new machine, by deleting the config directory _~/.openpnp_.
2. Proceed as usual. Configure machine, driver as _gcodeDriver_.
3. Run job _pnp-test.job.xml_
4. Verify machine executes job without problems
5. Go to [Solder paste] tab. Delete all entries listed there, for all jobs. Save job.
6. Exit openpnp.
7. Edit _machine.xml_: delete element \<paste-dispensers\> and all its children.
8. Run openpnp again. Go to the [Dispense] tab, under the camera window. Verify there is no dispenser listed there. Go to  [Solder paste] tab. Verify there is nothing listed there.
9. Start the job. Error message:
```
No default paste dispenser available on head H1.
<Try again> <Pause job>
```

**Comment by vonnieda** [comment] 2017-01-11 23:16
@dzach Okay, thanks. I will look into this. I think it's probably a bug in the glue processor. We fixed one in https://github.com/openpnp/openpnp/issues/369 but I think there is probably another.

**Comment by vonnieda** [comment] 2017-01-12 02:44
Okay, the issue is that the glue job processor tries to grab a reference to the default dispenser even if it doesn't have any work to do. We can fix this by deferring the reference until it's actually needed. I'm also going to remove the default glue and paste job processors since these are seldom used and are buggy and not finished.

**Comment by dzach** [comment] 2017-01-12 12:31
Does it mean there will be no paste capability, if the default paste processor is removed? Or one will have to include it manually?

**Comment by vonnieda** [comment] 2017-01-12 14:34
@dzach It will just be disabled by default, and users can enable it by adding the job processors.

**Closed** 2017-01-15 04:07 UTC
Labels: bug
