### ISSUE TITLE
Add a safe Z setting setting to board parameters to optimise Z movement

### ISSUE THREAD

**Issue by TomKeddie** [openpnp/openpnp#285] opened 2016-06-12 16:19 UTC
A safe Z setting would allow the head to be raised to a known safe offset rather than homing to zero.  

If the head is carrying a part (during place) the actual height to which the head is raised would need to take into account the part height so the bottom of the part was at the safe Z height.

Default value would be zero to maintain existing behaviour.

A check is needed to ensure the head is not raised beyond home.

(once a solution is agreed am happy to make these changes)

**Comment by vonnieda** [comment] 2016-06-13 02:38
Related to / duplicate of #96. Spoke with @TomKeddie about this and it looks like the current system will work for his machine.

**Closed by vonnieda** 2016-06-13 02:38 UTC
