### ISSUE TITLE
How to configure physical buttons to enable the machine to start working, or to stop or pause working?

### ISSUE THREAD

**Issue by xzbaijj** [openpnp/openpnp#1575] opened 2023-07-20 13:09 UTC
How to configure physical buttons to enable the machine to start working, or to stop or pause working?

**Comment by markmaker** [comment] 2023-07-20 15:52
Duplicate of #509.

See a proposed solution, here:
https://github.com/openpnp/openpnp/issues/509#issuecomment-733090095

I'm closing this, please follow #509 instead.

_Mark

**Closed by markmaker** 2023-07-20 15:52 UTC
