### ISSUE TITLE
Run placement from this component on

### ISSUE THREAD

**Issue by dandumit** [openpnp/openpnp#325] opened 2016-08-16 07:29 UTC
Hello All,

I had situation where I missed a functionality like "run from here" : 
I have managed to place ~40% of a board and I have lost the power or I have had to stop the job/machine due to various reasons .

In those cases would be very usefull to have a functionality to choose starting point from ordered ? list of components to be placed.

Thank you,
DAniel

**Comment by vonnieda** [comment] 2016-08-16 16:34
This is somewhat difficult due to the planner, since placements are not necessarily performed in the order they are shown. This is discussed a bit in #205, #258 and #219.

**Comment by vonnieda** [comment] 2016-12-29 17:52
This is a duplicate of #325.

**Closed by vonnieda** 2016-12-29 17:52 UTC
Labels: duplicate, enhancement
