### ISSUE TITLE
Feature request: pipeline pool

### ISSUE THREAD

**Issue by hukedev** [openpnp/openpnp#864] opened 2019-06-29 09:18 UTC
Most pipelines correlate with package-type but not always. So it is unecessary and very uncomfortable when a single pipeline (e.g. for R0402) is changed or improved, that all parts of this type have to be edited seperately.

Like nozzle tips are not fixed to specific nozzles anymore it would be fine if all pipelines would be in a single file (pipelines.xml) so that we could choose for each component/package-type a predefined pipeline. 

Each pipeline have an id and can be added, deleted or choosen with a simple dropdown in pipeline editor. 

Regarding openpnp2.0 improvements it would be good time now to implement this feature.

Thanks.

**Comment by vonnieda** [comment] 2019-06-29 16:56
Similar to / duplicate of #843

**Closed by vonnieda** 2019-06-29 16:56 UTC
