### ISSUE TITLE
Does the ScriptRun pipeline stage work with BeanShell scripts?

### ISSUE THREAD

**Issue by dzach** [openpnp/openpnp#540] opened 2017-05-07 16:44 UTC
# Problem Report
## Describe the Issue
I'm trying to run a simple script written in BeanShell java, but I am getting an error:
```
java.lang.Exception: Unable to find scriping engine for .openpnp/scripts/pipeline-test.bsh
```
It seems that openpnp does not recognize the `.bsh` file extension as a possible ScriptRun script, while it does recognize it as a script. 

## Steps to Reproduce
1. Place any file with a `.bsh` extension into the scripts directory.
2. start OpenPnP or the CvPipelineEditor and start editing a pipeline.
3. Add a new ScriptRun pipeline stage to the pipeline being edited.
4. Set the scipt file to be used by the stage
5. Observe the error in the lower right pane of the pipeline editor.

## Expected behavior
BeanShell scripts should work with the SriptRun pipeline stage, since they do work from the Scripts menu.
 
## Notes
Scripts work fine otherwise.
PC is 64 bit, Kubuntu 16.04:
```
uname -a
Linux desk 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vonnieda** [comment] 2017-05-07 17:13
@dzach Are you running the most recent code? There was a BSH scripting problem about 3-4 weeks ago that has been resolved.

**Comment by cri-s** [comment] 2017-05-07 17:14
Have you tested it on openpnp, not standalone editor, as this are different and advanced algorithm or loose feeder pipeline don't work on standalone editor.

**Comment by cri-s** [comment] 2017-05-07 17:16
The bsh problem was a win only problem, on Linux it worked to my knowledge.

**Comment by dzach** [comment] 2017-05-07 17:29
I get the same error in both the stand alone pipeline editor and the OpenPnP pipeline editor. But `.bsh` scripts work fine from the menu.

**Comment by vonnieda** [comment] 2017-05-07 17:50
Okay, I see what the issue is. We don't use the same scripting engine instance for the ScriptRun stage as OpenPnP uses so that it can be used outside of OpenPnP. This means that the bug fix for the BSH problem didn't make it here. We just need to add the BSH hack in Scripting.java to ScriptRun.java.

**Comment by vonnieda** [comment] 2017-05-07 17:55
Okay, pushed a fix. Let me know if it works for you please @dzach

**Closed** 2017-05-07 17:55 UTC
Labels: bug, help-wanted

**Comment by dzach** [comment] 2017-05-07 19:26
Yes, I don't get the error any more and I am able to run scripts.
Thanks @vonnieda !
